server:
  port: 8762
spring:
  application:
    name: service-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://tp:123456@localhost:8760/eureka/ #如果Eureka服务端不开启安全认证则为：http://localhost:8760/eureka/
feign:
  hystrix:
    enabled: true # feign启用hystrix，才能熔断、降级
  httpclient:
    enabled: true
  okhttp:
    enabled: false # 使用okHttp代替传统httpClient，性能更好
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #请求超时时间(默认1000ms)

