server:
  port: 9600
spring:
  application:
    name: dynamic-route-service
  # dev环境
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
  # 数据源
  redis:
    host: 120.78.215.14
    port: 6379
    password: tp123456
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:  tp123456
    url: jdbc:mysql://localhost:3306/dynamic-route?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: true
      pool-name: PbHikariCP
      connection-test-query: SELECT 1
      connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tp.dynamicroute.entity

# 注册中心
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://tp:123456@localhost:8760/eureka/ #如果Eureka服务端不开启安全认证则为：http://localhost:8760/eureka/
