server:
  port: 8760
spring:
  application:
    name: eurka-server
  security:
    user:
      name: tp
      password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #取消自注册
    fetchRegistry: false      #取消获取服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
